# Exported from Render on 2024-06-21T08:10:45Z
services:
- type: web
  name: movie8-nginx
  runtime: image
  image:
    url: docker.io/rekam/movie8-nginx:1.0
  plan: free
  region: singapore
  envVars:
    - key: PORT
      value: 80

- type: web
  name: movie8-php-fpm
  runtime: image
  image:
    url: docker.io/rekam/movie8-php-fpm:1.0
  plan: free
  region: singapore
  envVars:
    - key: PORT
      value: 9000
version: "1"
